"""Update created_at column (date) in tasks table

Revision ID: 9877c4c06c23
Revises: d058a5ad077c
Create Date: 2024-11-05 16:17:47.657995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9877c4c06c23'
down_revision: Union[str, None] = 'd058a5ad077c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'date')
    # ### end Alembic commands ###
