"""Add base_category and edit colors

Revision ID: c9a37a96f628
Revises: 76029384e23e
Create Date: 2024-12-14 22:29:51.863501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a37a96f628'
down_revision: Union[str, None] = '76029384e23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'color',
               existing_type=postgresql.ENUM('RED', 'GREEN', 'BLUE', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'BROWN', 'GREY', 'BLACK', 'WHITE', 'CYAN', 'LIME', 'TEAL', 'INDIGO', 'DEEP_PURPLE', 'LIGHT_BLUE', 'LIGHT_GREEN', 'LIGHT_GREY', 'DEEP_ORANGE', 'LIGHT_PINK', name='colors'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('base_category_id', sa.Integer(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', name='roles'), autoincrement=False, nullable=False))
    op.drop_column('users', 'base_category_id')
    op.alter_column('categories', 'color',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RED', 'GREEN', 'BLUE', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'BROWN', 'GREY', 'BLACK', 'WHITE', 'CYAN', 'LIME', 'TEAL', 'INDIGO', 'DEEP_PURPLE', 'LIGHT_BLUE', 'LIGHT_GREEN', 'LIGHT_GREY', 'DEEP_ORANGE', 'LIGHT_PINK', name='colors'),
               existing_nullable=False)
    # ### end Alembic commands ###
