"""fix

Revision ID: e04f3b534866
Revises: 74321ba5eead
Create Date: 2025-02-17 09:40:51.788690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04f3b534866'
down_revision: Union[str, None] = '74321ba5eead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
