"""Add categories table

Revision ID: f87938874434
Revises: a0791edcd2b7
Create Date: 2024-11-04 14:30:46.031363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87938874434'
down_revision: Union[str, None] = 'a0791edcd2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.Enum('RED', 'GREEN', 'BLUE', 'YELLOW', 'ORANGE', 'PURPLE', 'PINK', 'BROWN', 'GREY', 'BLACK', 'WHITE', 'CYAN', 'LIME', 'TEAL', 'INDIGO', 'DEEP_PURPLE', 'LIGHT_BLUE', 'LIGHT_GREEN', 'LIGHT_GREY', 'DEEP_ORANGE', 'LIGHT_PINK', name='colors'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
